title: Teddy's DEV Note
description: Connecting the Dots.

url:   https://teddylee777.github.io
image: images/logo.png

show_downloads: false
future:         true
# timezone:       Asia/Seoul

cayman-blog:
  date_format: "%b %-d, %Y"

theme: 

permalink: /:categories/:title

# social
author: Teddy Lee
disqus_shortname:   teddylee777
google_analytics:   UA-111508093-1

repository: teddylee777/teddylee777.github.io

highlighter: rouge
markdown:    kramdown
paginate:    5
paginate_path: "page:num"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# twitter:
#   username: lorepirri
#  site:
# facebook:
  #publisher: 1592372034171500
  #profile_id: 1809805629
  # app_id: 1798910940422432 # cayman-blog
  #authors: lorepirri
#  admins:

include: [".htaccess"]
exclude: ["lib", "config.rb", "Gemfile", "Capfile", "Gemfile.lock", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]

