title: Teddy's DEV Note
description: Connecting the Dots.

url:   //teddylee777.github.io
image: /images/logo.png

show_downloads: false
future:         true
# timezone:       Asia/Seoul

cayman-blog:
  date_format: "%b %-d, %Y"

theme: 

permalink: /:categories/:title

# social
author: Teddy Lee
disqus_shortname:   teddylee777
google_analytics:   UA-111508093-1

repository: teddylee777/teddylee777.github.io

highlighter: rouge
markdown:    kramdown

# root_dir: http://localhost:4000
category_dir: categories/
tag_dir: tag/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

include: [".htaccess"]
exclude: ["lib", "config.rb", "Gemfile", "Capfile", "Gemfile.lock", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]

