title: 이경록입니다.
description: 반갑습니다. 데이터 분석가 이경록입니다.

url:   # https://.github.io
image: /images/logo.png

show_downloads: false
future:         true

cayman-blog:
  date_format: "%b %-d, %Y"

theme: 

permalink: /:categories/:title

# social
author: # 이름을 입력하세요
disqus_shortname:   # disqus id를 입력하세요
google_analytics:   # UA-xxxxxxxxxx-1 구글 애널리틱스를 입력하세요

repository: # repository를 입력 하세요 ex) teddylee777/teddylee777.github.io

highlighter: rouge
markdown:    kramdown

# root_dir: http://localhost:4000
category_dir: categories/
tag_dir: tag/
categories: [data_science]

paginate: 10
paginate_path: "/posts/page:num/"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from


include: [".htaccess"]
exclude: ["lib", "config.rb", "Gemfile", "Capfile", "Gemfile.lock", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]

